#ifndef KNISHIO_MLKEM_MULTILEVEL_H
#define KNISHIO_MLKEM_MULTILEVEL_H

#ifndef MLK_CONFIG_API_NO_SUPERCOP
#define MLK_CONFIG_API_NO_SUPERCOP
#endif

#ifndef MLK_CONFIG_API_NO_RANDOMIZED_API
#define MLK_CONFIG_API_NO_RANDOMIZED_API
#endif

#define MLK_CONFIG_API_PARAMETER_SET 768
#define MLK_CONFIG_API_NAMESPACE_PREFIX mlkem768
#include "mlkem_native.h"
#undef MLK_CONFIG_API_PARAMETER_SET
#undef MLK_CONFIG_API_NAMESPACE_PREFIX
#undef MLK_H

#define MLK_CONFIG_API_PARAMETER_SET 1024
#define MLK_CONFIG_API_NAMESPACE_PREFIX mlkem1024
#include "mlkem_native.h"
#undef MLK_CONFIG_API_PARAMETER_SET
#undef MLK_CONFIG_API_NAMESPACE_PREFIX
#undef MLK_H

#endif /* KNISHIO_MLKEM_MULTILEVEL_H */
